version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(filename)s", "function": "%(funcName)s", "line": %(lineno)d}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: alimante.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: alimante_errors.log
    maxBytes: 5242880 # 5MB
    backupCount: 3
    encoding: utf8

  sensor_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: data/sensor_data.log
    maxBytes: 20971520 # 20MB
    backupCount: 10
    encoding: utf8

  alert_file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: detailed
    filename: alimante_alerts.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  alimante:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false

  alimante.sensors:
    level: INFO
    handlers: [sensor_file]
    propagate: false

  alimante.controllers:
    level: INFO
    handlers: [file]
    propagate: false

  alimante.services:
    level: INFO
    handlers: [file]
    propagate: false

  alimante.api:
    level: INFO
    handlers: [file]
    propagate: false

  alimante.safety:
    level: WARNING
    handlers: [alert_file, console]
    propagate: false

  alimante.ui:
    level: INFO
    handlers: [file]
    propagate: false

  alimante.loops:
    level: INFO
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
